name: Build App
on: 
   workflow_dispatch:
     branches: [ master ]
   watch:
     types: [started]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone repository
      run: git clone --depth=1 -b master https://github.com/kdrag0n/proton-clang clang
    
    - name: Build
      run: |
        cd kernel_oneplus_msm8998
        sudo rm -rf .git
        cd ..
        sudo tar -czvf ./5t.tar.gz ./kernel_oneplus_msm8998

    - name: Store generated APK file
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: ./5t.tar.gz
