name: Build App
on: 
   workflow_dispatch:
     branches: [ master ]
   watch:
     types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      run: git clone https://github.com/tao1996/FileView ./
    - name: Build

      run: |
        sh bu.sh
        ./gradlew

    - name: Store generated APK file
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: ./app/build/outputs/apk
