name: Build App
on: 
   workflow_dispatch:
     branches: [ master ]
   watch:
     types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      run: git clone https://github.com/bingduoduo1/bingduoduo/tree/7b04f89746e003eec18a112cf0222d90e6d767e9 ./
    - name: Build

      run: |
        bash bu.sh
        ./gradlew assembleDebug

    - name: Store generated APK file
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: ./app/build/outputs/apk
