name: Build App
on: 
   workflow_dispatch:
     branches: [ master ]
   watch:
     types: [started]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Clone repository
      run: |
        cd ~
        sudo curl -sL "https://codeload.github.com/termux/termux-app/zip/v0.65" > termux.zip
        sudo unzip termux.zip
        cd termux-app-0.65  
  
    - name: Build
      run: |
        sudo chmod 777 gradlew
        ./gradlew assembleDebug

    - name: Store generated APK file
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: ./app
